/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OlWcError {
        "errorMsg": string;
    }
    interface OlWcMessage {
        "args": Array<string>;
        "defaultMessage": string;
        "languageCode": string;
        "message": string;
        "messageKey": string;
        "model": { [key: string]: any };
        "plId": number;
    }
    interface OlWcSavedSearchItem {
        "ssItems": Array<SavedSearchEntity>;
    }
    interface OlWcSellerSavedSearch {
        "sectionTitle": string;
        "url": string;
    }
    interface OlWcSkeleton {
        "animation": string;
        "count": number;
        "customStyles": string;
        "height": string;
        "showWarnings": boolean;
        "variant": string;
        "width": string;
    }
}
declare global {
    interface HTMLOlWcErrorElement extends Components.OlWcError, HTMLStencilElement {
    }
    var HTMLOlWcErrorElement: {
        prototype: HTMLOlWcErrorElement;
        new (): HTMLOlWcErrorElement;
    };
    interface HTMLOlWcMessageElement extends Components.OlWcMessage, HTMLStencilElement {
    }
    var HTMLOlWcMessageElement: {
        prototype: HTMLOlWcMessageElement;
        new (): HTMLOlWcMessageElement;
    };
    interface HTMLOlWcSavedSearchItemElement extends Components.OlWcSavedSearchItem, HTMLStencilElement {
    }
    var HTMLOlWcSavedSearchItemElement: {
        prototype: HTMLOlWcSavedSearchItemElement;
        new (): HTMLOlWcSavedSearchItemElement;
    };
    interface HTMLOlWcSellerSavedSearchElement extends Components.OlWcSellerSavedSearch, HTMLStencilElement {
    }
    var HTMLOlWcSellerSavedSearchElement: {
        prototype: HTMLOlWcSellerSavedSearchElement;
        new (): HTMLOlWcSellerSavedSearchElement;
    };
    interface HTMLOlWcSkeletonElement extends Components.OlWcSkeleton, HTMLStencilElement {
    }
    var HTMLOlWcSkeletonElement: {
        prototype: HTMLOlWcSkeletonElement;
        new (): HTMLOlWcSkeletonElement;
    };
    interface HTMLElementTagNameMap {
        "ol-wc-error": HTMLOlWcErrorElement;
        "ol-wc-message": HTMLOlWcMessageElement;
        "ol-wc-saved-search-item": HTMLOlWcSavedSearchItemElement;
        "ol-wc-seller-saved-search": HTMLOlWcSellerSavedSearchElement;
        "ol-wc-skeleton": HTMLOlWcSkeletonElement;
    }
}
declare namespace LocalJSX {
    interface OlWcError {
        "errorMsg"?: string;
    }
    interface OlWcMessage {
        "args"?: Array<string>;
        "defaultMessage"?: string;
        "languageCode"?: string;
        "message"?: string;
        "messageKey"?: string;
        "model"?: { [key: string]: any };
        "plId"?: number;
    }
    interface OlWcSavedSearchItem {
        "ssItems"?: Array<SavedSearchEntity>;
    }
    interface OlWcSellerSavedSearch {
        "sectionTitle"?: string;
        "url"?: string;
    }
    interface OlWcSkeleton {
        "animation"?: string;
        "count"?: number;
        "customStyles"?: string;
        "height"?: string;
        "showWarnings"?: boolean;
        "variant"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "ol-wc-error": OlWcError;
        "ol-wc-message": OlWcMessage;
        "ol-wc-saved-search-item": OlWcSavedSearchItem;
        "ol-wc-seller-saved-search": OlWcSellerSavedSearch;
        "ol-wc-skeleton": OlWcSkeleton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ol-wc-error": LocalJSX.OlWcError & JSXBase.HTMLAttributes<HTMLOlWcErrorElement>;
            "ol-wc-message": LocalJSX.OlWcMessage & JSXBase.HTMLAttributes<HTMLOlWcMessageElement>;
            "ol-wc-saved-search-item": LocalJSX.OlWcSavedSearchItem & JSXBase.HTMLAttributes<HTMLOlWcSavedSearchItemElement>;
            "ol-wc-seller-saved-search": LocalJSX.OlWcSellerSavedSearch & JSXBase.HTMLAttributes<HTMLOlWcSellerSavedSearchElement>;
            "ol-wc-skeleton": LocalJSX.OlWcSkeleton & JSXBase.HTMLAttributes<HTMLOlWcSkeletonElement>;
        }
    }
}
